name: Lint & Type checks

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 14

      - name: Run Prettier and ESlint
        run: |
          yarn install
          yarn lint
      - name: Run Prettier and ESlint
        run: |
          yarn tsc
