name: Lint & Type checks

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 14

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Prettier and ESlint
        run: |
          yarn lint

  types:
    name: Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 14

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Typescript checks
        run: |
          yarn tsc
